import { Pool } from "pg"

interface ColumnInfo {
  name: string
  type: string
  nullable: boolean
  default: string | null
  isIdentity: boolean
}

export async function generateBackup(connectionString: string): Promise<AsyncIterable<string>> {
  const pool = new Pool({ connectionString })

  try {
    const schemaResult = await pool.query(`
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'public'
        AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `)

    const tables = schemaResult.rows.map((r: { table_name: string }) => r.table_name)

    async function* generate() {
      const now = new Date().toISOString().replace(/T/, " ").replace(/\..+/, "")
      yield `-- ============================================================\n`
      yield `-- PDM Têxtil - Backup do Banco de Dados\n`
      yield `-- Gerado em: ${now}\n`
      yield `-- Conexão: ${connectionString.replace(/\/\/[^:]+:[^@]+@/, "//***:***@")}\n`
      yield `-- ============================================================\n\n`
      yield `BEGIN;\n\n`

      for (const table of tables) {
        const colResult = await pool.query(
          `SELECT
            c.column_name,
            c.data_type,
            c.is_nullable,
            c.column_default,
            c.is_identity
          FROM information_schema.columns c
          WHERE c.table_schema = 'public' AND c.table_name = $1
          ORDER BY c.ordinal_position`,
          [table]
        )

        const columns: ColumnInfo[] = colResult.rows.map((r: {
          column_name: string
          data_type: string
          is_nullable: string
          column_default: string | null
          is_identity: string
        }) => ({
          name: r.column_name,
          type: r.data_type,
          nullable: r.is_nullable === "YES",
          default: r.column_default,
          isIdentity: r.is_identity === "YES",
        }))

        const colDefs = columns
          .map(col => {
            let def = `  "${col.name}" ${col.type}`
            if (col.isIdentity) def += " GENERATED BY DEFAULT AS IDENTITY"
            if (!col.nullable) def += " NOT NULL"
            if (col.default && !col.isIdentity) def += ` DEFAULT ${col.default}`
            return def
          })
          .join(",\n")

        yield `-- Tabela: ${table}\n`
        yield `DROP TABLE IF EXISTS "${table}" CASCADE;\n`
        yield `CREATE TABLE "${table}" (\n${colDefs}\n);\n\n`

        const dataResult = await pool.query(`SELECT * FROM "${table}"`)
        if (dataResult.rows.length > 0) {
          const colNames = columns.map(c => `"${c.name}"`).join(", ")
          for (const row of dataResult.rows) {
            const values = columns.map(col => {
              const val = row[col.name]
              if (val === null || val === undefined) return "NULL"
              if (typeof val === "number") return String(val)
              if (typeof val === "boolean") return val ? "true" : "false"
              if (val instanceof Date) return `'${val.toISOString()}'`
              const escaped = String(val).replace(/'/g, "''")
              return `'${escaped}'`
            })
            yield `INSERT INTO "${table}" (${colNames}) VALUES (${values.join(", ")});\n`
          }
          yield "\n"
        }
      }

      yield `COMMIT;\n`
      yield `-- ============================================================\n`
      yield `-- Backup concluído em ${new Date().toISOString().replace(/T/, " ").replace(/\..+/, "")}\n`
      yield `-- ============================================================\n`
    }

    return generate()
  } catch (err) {
    await pool.end()
    throw err
  }
}
