import { neon } from "@neondatabase/serverless"
import dotenv from "dotenv"
dotenv.config({ path: ".env.local" })
const sql = neon(process.env.DATABASE_URL)

// Build each lesson content as an array of lines, then join
const lessons = {}

lessons[1] = [
  '## 🌟 O que é CRM?',
  '',
  'CRM significa **Customer Relationship Management** — ou, em português: **Gestão do Relacionamento com o Cliente**.',
  '',
  'Antes do CRM, cada vendedor tinha suas anotações em papéis, blocos, WhatsApp, cabeça... **Cada um do seu jeito**. O CRM é o **lugar único** onde toda a história do cliente fica registrada:',
  '',
  '- 📞 Quem ligou, quando e por quê',
  '- 📧 O que foi prometido',
  '- 🤝 Quais visitas já foram feitas',
  '- 💰 Quais propostas estão em andamento',
  '- 📊 Quantas vendas foram fechadas ou perdidas',
  '',
  '---',
  '',
  '### Por que a PDM Têxtil está adotando o CRM?',
  '',
  '| Antes (sem CRM) | Agora (com CRM) |',
  '| :--- | :--- |',
  '| Informação espalhada | Tudo em um lugar só |',
  '| Cliente esquecido | Histórico completo |',
  '| Vendas dependem de uma pessoa | Time trabalha junto |',
  '| Decisão no achismo | Decisão com dados |',
  '| Retrabalho | Eficiência |',
  '',
  '> 💡 **Mensagem do Desenvolvedor:** *"Este CRM foi construído com carinho para ajudar **você** a vender mais e melhor. Não é um sistema de controle — é uma ferramenta de **libertação**. Use com orgulho!"*',
  '',
  '---',
  '',
  '### O que muda no meu dia a dia?',
  '',
  '| Situação | Antes | Agora |',
  '| :--- | :--- | :--- |',
  '| Telefone do cliente | "Deixa eu ver onde anotei..." | Abre o CRM, busca, **pronto** |',
  '| Proposta enviada | "Eu juro que mandei..." | Data, status, valor — **sem achismo** |',
  '| Histórico perdido | "O fulano saiu, perdemos tudo..." | O histórico **fica na Pessoa** |',
  '',
  '---',
  '',
  '### Para quem é o CRM?',
  '',
  '| Perfil | Uso |',
  '| :--- | :--- |',
  '| ✅ **Comercial** | Uso diário (vendedores, representantes, gerentes) |',
  '| ✅ **Marketing** | Saber quais campanhas geram leads |',
  '| ✅ **Diretoria** | Acompanhar indicadores |',
  '| ✅ **Administrativo** | Propostas e contratos |',
  '| ✅ **Todos que falam com cliente** | Sim, você também! |',
  '',
  '---',
  '',
  '### Como começar?',
  '',
  'Não precisa saber tudo de uma vez. Vá módulo por módulo. Comece por este treinamento, depois **abra o CRM e explore**. A melhor forma de aprender é **usando**. 💙',
  '',
  '---',
  '',
  '*"CRM não é sobre tecnologia, é sobre **pessoas**. Pessoas atendendo melhor outras pessoas." — O Desenvolvedor*',
].join("\n")

lessons[2] = [
  '## 🖥️ Acessando o CRM',
  '',
  '1. Abra seu navegador (Chrome, Edge, Firefox)',
  '2. Acesse o endereço informado pela sua equipe de TI',
  '3. Faça login com seu **usuário e senha** (mesmo do sistema)',
  '',
  '---',
  '',
  '### Primeira tela: o Dashboard',
  '',
  'Assim que você entrar, vai ver o **Dashboard** — o painel principal do CRM. Ele mostra tudo que importa de um pulo só:',
  '',
  '| Área | O que mostra |',
  '| :--- | :--- |',
  '| 📊 **Resumo** | Pessoas, leads, oportunidades ativas |',
  '| 💰 **Previsão de Vendas** | Quanto está previsto para este mês |',
  '| 📈 **Funil** | Oportunidades em cada etapa |',
  '| 🔄 **Conversão** | Taxa de conversão |',
  '| 🏆 **Top Pessoas** | Maiores oportunidades |',
  '| ⏰ **Timeline Recente** | Últimas atividades |',
  '',
  '---',
  '',
  '### Barra de navegação (menu lateral)',
  '',
  'No canto esquerdo, você encontra o menu. Clique em **Comercial → CRM**:',
  '',
  '```',
  '📊 Comercial',
  '  └── 🤝 CRM',
  '       ├── 📊 Dashboard',
  '       ├── 👤 Pessoas',
  '       ├── 👥 Contatos',
  '       ├── 📋 Leads',
  '       ├── 💼 Oportunidades',
  '       ├── 📄 Propostas',
  '       ├── 📅 Visitas',
  '       ├── ✅ Tarefas',
  '       ├── 📈 Relatórios',
  '       ├── 💬 WhatsApp',
  '       ├── 📣 Campanhas',
  '       ├── ⚙️ Configurações',
  '       └── 🎓 Treinamento',
  '```',
  '',
  '---',
  '',
  '### Dicas de navegação',
  '',
  '| Ação | Como fazer |',
  '| :--- | :--- |',
  '| 🔍 **Busca** | Ctrl+F para achar registros em listas |',
  '| 📱 **Responsivo** | Funciona no celular também |',
  '| 🌙 **Modo escuro** | Ative nas configurações |',
  '| ℹ️ **Botão "i"** | Clique para ver explicação rápida da tela |',
  '',
  'No canto superior direito, clique no seu nome para ver seus dados ou sair do sistema.',
  '',
  '---',
  '',
  '> ✅ **Próximo módulo:** Pessoas — A Base de Tudo',
].join("\n")

lessons[3] = [
  '## 👤 O que é uma "Pessoa" no CRM?',
  '',
  'No CRM da PDM Têxtil, uma **Pessoa** representa uma **entidade** — que pode ser:',
  '',
  '| Tipo | Exemplo |',
  '| :--- | :--- |',
  '| 🏢 **Pessoa Jurídica (Empresa)** | Confecção ABC Ltda, Tecidos XYZ S.A. |',
  '| 👤 **Pessoa Física (Individual)** | Profissional autônomo, MEI, ou cliente pessoa física |',
  '',
  '"Pessoa" é o **registro central** do CRM. Pode ser uma empresa com CNPJ ou uma pessoa física sem CNPJ. Tudo gira em torno dela.',
  '',
  '> 🌟 **Regra de ouro:** *Sempre cadastre a Pessoa primeiro! Depois adicione contatos, oportunidades, visitas, etc.*',
  '',
  '---',
  '',
  '### Criando uma Pessoa',
  '',
  '1. Vá em **CRM → Pessoas**',
  '2. Clique em **"Nova Pessoa"**',
  '3. Preencha os campos:',
  '',
  '| Campo | Obrigatório | O que é | Dica |',
  '| :--- | :---: | :--- | :--- |',
  '| **Razão Social** | ✅ Sim | Nome oficial (da empresa ou do indivíduo) | Sem abreviações |',
  '| **Nome Fantasia** | Não | Nome popular | Como o cliente se apresenta |',
  '| **CNPJ** | Não* | CNPJ com pontuação. Deixe em branco se PF | 00.000.000/0001-00 |',
  '| **Segmento** | Não | Ramo de atuação | Confecção, Lavanderia, Têxtil |',
  '| **Porte** | Não | Tamanho | ME, EPP, Médio, Grande |',
  '| **Site** | Não | Endereço do site | Opcional |',
  '| **Status** | Não | Situação atual | NOVO (padrão), ATIVO, INATIVO |',
  '| **Responsável** | Não | Quem cuida da conta | Geralmente você |',
  '',
  '> *CNPJ é único se preenchido — não obrigatório para pessoa física.*',
  '',
  '---',
  '',
  '### Depois de salvar',
  '',
  'Após criar, você vai para a **página de detalhe**. Lá você encontra:',
  '',
  '| Aba | Descrição |',
  '| :--- | :--- |',
  '| 📋 **Dados** | Resumo completo do registro |',
  '| 👥 **Contatos** | Pessoas vinculadas (funcionários, sócios, familiares) |',
  '| 💼 **Oportunidades** | Negócios em andamento |',
  '| 📄 **Propostas** | Propostas enviadas |',
  '| 📅 **Visitas** | Visitas realizadas / agendadas |',
  '| ✅ **Tarefas** | Compromissos pendentes |',
  '| 💬 **WhatsApp** | Conversas registradas |',
  '| ⏰ **Timeline** | Histórico completo |',
  '',
  '> 💡 Capriche no cadastro! Dados completos fazem toda a diferença nos relatórios e nas sugestões da IA.',
].join("\n")

lessons[4] = [
  '## 🔍 Como encontrar uma Pessoa',
  '',
  'Na lista de pessoas, você pode:',
  '',
  '1. **Buscar pelo nome** — Digite na barra de busca',
  '2. **Buscar pelo CNPJ** — Funciona também',
  '3. **Filtrar por status** — NOVO, ATIVO, INATIVO',
  '4. **Filtrar por responsável** — Ver só as suas ou de um colega',
  '5. **Ordenar** — Por nome, data, status',
  '',
  '---',
  '',
  '### Editando uma Pessoa',
  '',
  '1. Clique no nome da Pessoa para abrir o detalhe',
  '2. Clique em **Editar** (ícone de lápis ✏️)',
  '3. Altere os campos necessários',
  '4. Salve',
  '',
  '> ⚠️ Atenção: O CNPJ não pode ser alterado depois de criado (para evitar duplicidade). Se cadastrou errado, crie uma nova e inative a antiga.',
  '',
  '---',
  '',
  '### Status das pessoas',
  '',
  '| Status | Significado | O que fazer |',
  '| :--- | :--- | :--- |',
  '| 🆕 **NOVO** | Acabou de ser cadastrada | Primeiro contato pendente |',
  '| ✅ **ATIVO** | Cliente ativo, com negócios | Manter relacionamento |',
  '| 💤 **INATIVO** | Sem movimento há muito tempo | Tentar reativar |',
  '| 🔍 **PROSPECTO** | Potencial, ainda não comprou | Qualificar e converter |',
  '',
  '---',
  '',
  '### Duplicidade de Pessoas',
  '',
  'O sistema **não permite** dois CNPJs iguais. Se encontrar duplicatas:',
  '',
  '1. Mantenha a Pessoa com mais informações',
  '2. Migre contatos e oportunidades para ela',
  '3. Inative a duplicada',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> **Mantenha os dados sempre atualizados!** Uma Pessoa com telefone errado, site quebrado ou segmento em branco vale muito menos. Reserve 5 minutos por dia para revisar seus registros.',
].join("\n")

lessons[5] = '' // skip - already well formatted

lessons[6] = [
  '## 📋 O que é um Lead?',
  '',
  '**Lead** é uma pessoa que **demonstrou interesse** nos produtos da PDM Têxtil, mas **ainda não é cliente**.',
  '',
  '### Exemplos de leads',
  '',
  '- Alguém que preencheu um formulário no site',
  '- Uma indicação de outro cliente',
  '- Alguém que mandou WhatsApp perguntando preços',
  '- Um visitante de feira que deixou o cartão',
  '- Uma empresa que você pesquisou e parece promissora',
  '',
  '> 🔄 **Jornada:** Lead → Oportunidade → Proposta → Cliente',
  '',
  '---',
  '',
  '### Cadastrando um lead',
  '',
  'Vá em **CRM → Leads → Novo Lead** e informe os dados:',
  '',
  '| Campo | Obrigatório | Descrição |',
  '| :--- | :---: | :--- |',
  '| **Nome** | ✅ Sim | Nome da pessoa |',
  '| **E-mail** | Não | Para contato |',
  '| **Telefone** | Não | Telefone fixo |',
  '| **Celular** | Não | WhatsApp |',
  '| **Pessoa** | Não | A qual Pessoa está vinculado |',
  '| **Cargo** | Não | Cargo na Pessoa |',
  '| **Origem** | Padrão: OUTRO | SITE, INDICACAO, FEIRA, WHATSAPP, LIGACAO, REDE_SOCIAL |',
  '| **Status** | Padrão: NOVO | NOVO, CONTATADO, QUALIFICADO, CONVERTIDO, PERDIDO |',
  '| **Descrição** | Não | Como conheceu, o que precisa |',
  '| **Responsável** | Não | Quem vai cuidar |',
  '',
  '---',
  '',
  '### Origens do lead',
  '',
  '| Origem | Exemplo |',
  '| :--- | :--- |',
  '| 📱 **SITE** | Formulário de contato no site |',
  '| 🙋 **INDICACAO** | "O João da empresa X indicou vocês" |',
  '| 🎪 **FEIRA** | Cartão coletado em evento |',
  '| 💬 **WHATSAPP** | Mensagem no WhatsApp comercial |',
  '| 📞 **LIGACAO** | Telefonou para a empresa |',
  '| 🌐 **REDE_SOCIAL** | Instagram, Facebook, LinkedIn |',
  '',
  '---',
  '',
  '### Status do lead',
  '',
  '| Status | O que significa | Próximo passo |',
  '| :--- | :--- | :--- |',
  '| 🆕 **NOVO** | Acabou de chegar | Entrar em contato |',
  '| 📞 **CONTATADO** | Já falamos com ele | Qualificar |',
  '| 🎯 **QUALIFICADO** | Tem potencial real | Criar oportunidade |',
  '| ✅ **CONVERTIDO** | Virou cliente | Mover para Pessoa / Oportunidade |',
  '| ❌ **PERDIDO** | Não vai dar negócio | Registrar motivo |',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> **Nem todo lead vira cliente, mas todo lead merece atenção.** Responda rápido, seja educado e registre TUDO no CRM.',
].join("\n")

lessons[7] = [
  '## 🔍 Gerenciando leads',
  '',
  'Na lista de **Leads** você pode:',
  '- Buscar por nome',
  '- Filtrar por **origem**',
  '- Filtrar por **status**',
  '- Filtrar por **responsável**',
  '- Ver o **score** (nota de 0 a 100)',
  '',
  '---',
  '',
  '### Score de lead',
  '',
  'O **Score** é uma nota de **0 a 100** que indica o potencial do lead:',
  '',
  '| Score | Cor | Significado |',
  '| :---: | :---: | :--- |',
  '| 🟢 **70+** | Verde | Lead quente! Grande potencial |',
  '| 🟡 **40-69** | Amarelo | Lead morno, merece atenção |',
  '| 🔴 **< 40** | Vermelho | Lead frio, baixo potencial |',
  '',
  '### Como o score é calculado?',
  '',
  '| Fator | O que considera |',
  '| :--- | :--- |',
  '| Segmento | A Pessoa é de um segmento promissor? |',
  '| Porte | Porte da Pessoa |',
  '| Origem | Indicação vale mais que site |',
  '| Histórico | Comportamento similar a clientes que converteram |',
  '',
  '---',
  '',
  '### O que fazer com cada lead',
  '',
  '| Score | Ação |',
  '| :---: | :--- |',
  '| 🟢 **70+** | **Prioridade máxima!** Contate imediatamente |',
  '| 🟡 **40-69** | Entre em contato, busque qualificar |',
  '| 🔴 **< 40** | Coloque em nutrição, não descarte |',
  '',
  '### Convertendo lead em oportunidade',
  '',
  'Quando um lead está **QUALIFICADO**:',
  '1. Abra o lead',
  '2. Clique em **"Criar Oportunidade"**',
  '3. Pronto! Agora é uma oportunidade de verdade',
  '',
  '> 💡 Se o lead tem Pessoa vinculada, ótimo. Se não, crie a Pessoa na hora da conversão.',
].join("\n")

lessons[8] = [
  '## 💼 O que é uma Oportunidade?',
  '',
  '**Oportunidade** é uma **venda em potencial** que está sendo trabalhada. Diferente do lead (primeiro contato), a oportunidade já tem um negócio sendo discutido.',
  '',
  '> 🎯 **Resumo:** Lead é "quem". Oportunidade é "o que".',
  '',
  '---',
  '',
  '### Criando uma oportunidade',
  '',
  '1. Vá em **CRM → Oportunidades → Nova Oportunidade**',
  '2. Ou dentro de uma **Pessoa**, vá na aba Oportunidades',
  '',
  '| Campo | Obrigatório | Descrição |',
  '| :--- | :---: | :--- |',
  '| **Título** | ✅ Sim | Ex: "Venda de 500m de tecido Oxford" |',
  '| **Descrição** | Não | Detalhes do que o cliente precisa |',
  '| **Valor Estimado** | Não | Quanto vale o negócio |',
  '| **Status** | Padrão: NOVO | Etapa do pipeline |',
  '| **Lead** | Não | De qual lead veio |',
  '| **Pessoa** | Não | Para qual Pessoa |',
  '| **Contato** | Não | Com quem está falando |',
  '| **Responsável** | Não | Quem está tocando |',
  '| **Data Fechamento** | Não | Previsão de fechamento |',
  '| **Probabilidade** | Não | Chance de fechar (0-100%) |',
  '',
  '---',
  '',
  '### Pipeline de vendas',
  '',
  '```',
  '     🆕 NOVO',
  '        ⬇️',
  '     📞 QUALIFICACAO',
  '        ⬇️',
  '     📄 PROPOSTA',
  '        ⬇️',
  '     🤝 NEGOCIACAO',
  '        ⬇️',
  '  ┌─────────┴─────────┐',
  '  ✅ FECHADO_GANHO    ❌ FECHADO_PERDIDO',
  '```',
  '',
  '| Etapa | O que fazer | Probabilidade |',
  '| :--- | :--- | :---: |',
  '| 🆕 **NOVO** | Entender a necessidade | 10% |',
  '| 📞 **QUALIFICACAO** | Descobrir orçamento, prazo, decisor | 25% |',
  '| 📄 **PROPOSTA** | Enviar proposta formal | 50% |',
  '| 🤝 **NEGOCIACAO** | Ajustar preço / prazo / condições | 75% |',
  '| ✅ **FECHADO_GANHO** | VENDEU! 🎉 | 100% |',
  '| ❌ **FECHADO_PERDIDO** | Registrar motivo | — |',
  '',
  '> 💡 **Priorize:** Foque nas oportunidades em NEGOCIACAO com 75%+ de probabilidade.',
  '',
  '---',
  '',
  '### Motivo de perda',
  '',
  'Sempre registre **por que** uma oportunidade foi perdida:',
  '',
  '| Motivo | Descrição |',
  '| :--- | :--- |',
  '| ⚠️ **PRECO** | Preço muito alto |',
  '| ⚠️ **PRAZO** | Prazo não atendeu |',
  '| ⚠️ **CONCORRENCIA** | Escolheu outro fornecedor |',
  '| ⚠️ **SEM_NEED** | Não tinha necessidade real |',
  '| ⚠️ **OUTRO** | Outros motivos |',
  '',
  '> Isso ajuda a diretoria a entender **por que estamos perdendo vendas** e tomar ações corretivas.',
].join("\n")

lessons[9] = [
  '## 📊 O que é o Kanban?',
  '',
  'O Kanban é um jeito **visual** de ver suas oportunidades organizadas por etapa:',
  '',
  '```',
  '┌──────────┐ ┌──────────────┐ ┌──────────┐ ┌────────────┐ ┌─────────────┐ ┌──────────────┐',
  '│  NOVO    │ │ QUALIFICACAO │ │ PROPOSTA │ │ NEGOCIACAO │ │FECHADO_GANHO│FECHADO_PERDIDO│',
  '│  [Card]  │ │ [Card]       │ │ [Card]   │ │ [Card]     │ │ [Card]      │ │ [Card]       │',
  '│  [Card]  │ │              │ │          │ │            │ │             │ │              │',
  '└──────────┘ └──────────────┘ └──────────┘ └────────────┘ └─────────────┘ └──────────────┘',
  '```',
  '',
  '---',
  '',
  '### Como usar',
  '',
  '1. Vá em **CRM → Oportunidades → Kanban**',
  '2. Veja todas as oportunidades em cards',
  '3. **Arraste** um card de coluna para mudar o status',
  '',
  'Cada card mostra: título, valor estimado, Pessoa, responsável e data prevista.',
  '',
  '---',
  '',
  '### Por que o Kanban é útil?',
  '',
  '| Situação | Antes | Agora |',
  '| :--- | :--- | :--- |',
  '| Propostas em negociação | "Não sei quantas são" | Vejo todas de uma vez |',
  '| Pipeline completo | "Preciso perguntar pra cada um" | O quadro mostra tudo |',
  '| Status desatualizado | "Esqueci de atualizar" | Arrasto e pronto |',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> **Atualize o Kanban todo dia!** No começo do expediente, gaste 2 minutos arrastando cada oportunidade para a etapa correta.',
].join("\n")

lessons[10] = [
  '## 📄 O que é uma Proposta?',
  '',
  'Proposta é o **documento formal** enviado ao cliente com o que está sendo vendido, preço, condições de pagamento e prazo de entrega.',
  '',
  '---',
  '',
  '### Criando uma proposta',
  '',
  '1. Vá em **CRM → Propostas → Nova Proposta**',
  '2. Ou dentro de uma **Oportunidade**, clique em "Criar Proposta"',
  '',
  '| Campo | Obrigatório | Descrição |',
  '| :--- | :---: | :--- |',
  '| **Título** | ✅ Sim | Ex: "Proposta de fornecimento Oxford" |',
  '| **Pessoa** | ✅ Sim | Para quem é |',
  '| **Oportunidade** | Não | Vincular à oportunidade |',
  '| **Valor** | Não | Valor total da proposta |',
  '| **Descrição** | Não | Detalhamento do proposto |',
  '| **Condições de Pagamento** | Não | Ex: 30/60/90 dias |',
  '| **Prazo de Entrega** | Não | Ex: "30 dias após aprovação" |',
  '| **Arquivo** | Não | URL do PDF ou documento |',
  '',
  '---',
  '',
  '### Status da proposta',
  '',
  '| Status | Significado |',
  '| :--- | :--- |',
  '| 📤 **ENVIADA** | Acabou de enviar para o cliente |',
  '| ✅ **ACEITA** | Cliente aprovou! 🎉 |',
  '| ❌ **RECUSADA** | Cliente recusou |',
  '| 🔄 **REVISAO** | Cliente pediu alterações |',
  '',
  '| Cor | Status | Ação |',
  '| :---: | :--- | :--- |',
  '| 🔵 Azul | Enviadas | Aguardando retorno |',
  '| 🟡 Amarelo | Em revisão | Precisa ajustar |',
  '| 🟢 Verde | Aceitas | Comemore! 🎉 |',
  '| 🔴 Vermelho | Recusadas | Entenda o motivo |',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> **Uma proposta parada há mais de 15 dias provavelmente está perdida.** Se o status é ENVIADA há semanas, ligue para o cliente.',
].join("\n")

lessons[11] = [
  '## 📅 O que é uma Visita?',
  '',
  'Visita é qualquer **interação programada** com o cliente:',
  '',
  '| Tipo | Descrição |',
  '| :--- | :--- |',
  '| 🏢 **PRESENCIAL** | Você foi até o cliente |',
  '| 📹 **VIDEO** | Chamada de vídeo (Zoom, Meet, WhatsApp) |',
  '| 📞 **TELEFONE** | Ligação telefônica agendada |',
  '',
  '> 🌟 **Regra de ouro:** Toda interação importante com o cliente merece ser registrada como visita!',
  '',
  '---',
  '',
  '### Agendando uma visita',
  '',
  'Vá em **CRM → Visitas → Nova Visita**:',
  '',
  '| Campo | Obrigatório | Descrição |',
  '| :--- | :---: | :--- |',
  '| **Pessoa** | ✅ Sim | Onde será a visita |',
  '| **Data da Visita** | ✅ Sim | Quando |',
  '| **Tipo** | Padrão: PRESENCIAL | Presencial, Vídeo ou Telefone |',
  '| **Contato** | Não | Com quem vai falar |',
  '| **Oportunidade** | Não | Se for sobre um negócio |',
  '| **Status** | Padrão: AGENDADA | AGENDADA, REALIZADA, CANCELADA |',
  '| **Relato** | Não | Preencha DEPOIS da visita |',
  '| **Fotos** | Não | Fotos da visita |',
  '',
  '---',
  '',
  '### Fluxo da visita',
  '',
  '```',
  '📅 AGENDADA → ✅ REALIZADA → (relato + fotos)',
  '            ↘ ❌ CANCELADA → (motivo)',
  '```',
  '',
  '### O relato',
  '',
  'Depois da visita, preencha: o que o cliente disse, qual o humor, há novidades, próximos passos.',
  '',
  '> 💡 Um bom relato é objetivo, mas completo. Escreva como se estivesse contando para um colega.',
  '',
  '### Fotos',
  '',
  'Se for presencial, **tire fotos** do produto, da equipe e do ambiente.',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> **Nunca faça uma visita sem registrar no CRM antes.** O relato é a prova do trabalho bem feito.',
].join("\n")

lessons[12] = [
  '## ✅ O que é uma Tarefa?',
  '',
  'Tarefa é um **compromisso** ou **lembrete** que você cria para não esquecer:',
  '',
  '| Tipo | Exemplo |',
  '| :--- | :--- |',
  '| 📞 **LIGACAO** | "Ligar para o João amanhã às 10h" |',
  '| 🤝 **REUNIAO** | "Reunião com equipe comercial" |',
  '| 📄 **PROPOSTA** | "Enviar proposta revisada" |',
  '| 📌 **TAREFA** | "Atualizar planilha de preços" |',
  '',
  '---',
  '',
  '### Criando uma tarefa',
  '',
  '1. Vá em **CRM → Tarefas → Nova Tarefa**',
  '2. Ou dentro de uma **Pessoa / Oportunidade**',
  '',
  '| Campo | Obrigatório | Descrição |',
  '| :--- | :---: | :--- |',
  '| **Título** | ✅ Sim | O que precisa ser feito |',
  '| **Tipo** | Padrão: TAREFA | LIGACAO, REUNIAO, PROPOSTA, TAREFA |',
  '| **Descrição** | Não | Detalhes |',
  '| **Data Prevista** | Não | Quando fazer |',
  '| **Data Conclusão** | Não | Preenche quando concluir |',
  '| **Status** | Padrão: PENDENTE | PENDENTE, CONCLUIDA, CANCELADA |',
  '| **Responsável** | Não | Quem vai fazer |',
  '| **Pessoa** | Não | Relacionar a uma Pessoa |',
  '| **Oportunidade** | Não | Relacionar a uma oportunidade |',
  '',
  '---',
  '',
  '### Gerenciando tarefas',
  '',
  '- 📋 Todas as tarefas pendentes',
  '- 📅 Organizadas por data',
  '- 🔍 Filtrar por tipo, status, Pessoa',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> **Crie tarefas para TUDO.** Com o CRM cuidando dos lembretes, sua cabeça fica livre para vender.',
  '',
  '| Hábito | Como fazer |',
  '| :--- | :--- |',
  '| "Ligar amanhã" | Criar tarefa: LIGACAO |',
  '| "Enviar proposta" | Criar tarefa: PROPOSTA |',
  '| "Não esquecer" | Criar tarefa: TAREFA |',
].join("\n")

lessons[13] = [
  '## ⏰ O que é a Timeline?',
  '',
  'A **Timeline** é o **histórico completo** de tudo que aconteceu com uma Pessoa. Ela é **automática**.',
  '',
  '### O que aparece',
  '',
  '| Evento | Automático? |',
  '| :--- | :---: |',
  '| 👤 **Pessoa criada** | ✅ |',
  '| 👤 **Contato adicionado** | ✅ |',
  '| 💼 **Oportunidade criada** | ✅ |',
  '| 🔄 **Oportunidade mudou de etapa** | ✅ |',
  '| 📄 **Proposta enviada** | ✅ |',
  '| 📅 **Visita agendada / realizada** | ✅ |',
  '| ✅ **Tarefa concluída** | ✅ |',
  '| 💬 **Mensagem WhatsApp** | ✅ |',
  '',
  '---',
  '',
  '### Por que é importante?',
  '',
  '```',
  'Cliente: "Mas vocês prometeram que tal coisa..."',
  'Antes:  "Hmm, não me lembro..."',
  'Agora:  *abre a timeline* "No dia 15/03 foi registrado..."',
  '```',
  '',
  '> **A timeline é a prova do seu trabalho!**',
  '',
  '---',
  '',
  '### Como acessar',
  '',
  'Dentro de qualquer **Pessoa**, role para baixo ou clique na aba **Timeline**. Eventos em ordem cronológica (do mais recente para o mais antigo).',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> **Sempre verifique a timeline primeiro.** Evita repetir perguntas e mostra que você se importa com o histórico.',
].join("\n")

lessons[14] = [
  '## 📊 Visão Geral do Dashboard',
  '',
  'O Dashboard é a **primeira tela** ao entrar no CRM. Ele dá um **raio-x completo** do seu negócio em segundos.',
  '',
  '### Cards de resumo',
  '',
  '```',
  '┌──────────┐ ┌──────────┐ ┌──────────┐ ┌──────────┐',
  '│ Pessoas  │ │  Leads   │ │ Oportun. │ │ Prop.    │',
  '│   150    │ │    45    │ │   28     │ │   12     │',
  '└──────────┘ └──────────┘ └──────────┘ └──────────┘',
  '```',
  '',
  'Cada card mostra o **total ativo**. Clique para ir direto à lista.',
  '',
  '---',
  '',
  '### Funil de vendas',
  '',
  '```',
  'NOVO:         ████████████████  10',
  'QUALIFICAÇÃO: ██████████         8',
  'PROPOSTA:     ███████            5',
  'NEGOCIAÇÃO:   ████               3',
  '```',
  '',
  '> 📈 **Funil saudável:** Mais oportunidades no topo (NOVO) do que no fundo.',
  '',
  '---',
  '',
  '### Indicadores',
  '',
  '| Indicador | Descrição |',
  '| :--- | :--- |',
  '| 💰 **Previsão de Vendas** | Valor total por mês |',
  '| 📊 **Conversão** | Taxa lead → oportunidade → proposta → fechado |',
  '| 🏆 **Top Pessoas** | Pessoas com maior valor em oportunidades |',
  '| ⏰ **Timeline Recente** | Últimas atividades |',
  '| ➕ **Ações Rápidas** | Criar: Pessoa, lead, oportunidade, visita |',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> **Comece o dia pelo Dashboard.** 5 min de manhã + 5 min à noite fazem milagres!',
].join("\n")

lessons[15] = [
  '## 📈 O que são os Relatórios?',
  '',
  'Enquanto o Dashboard mostra o **agora**, os Relatórios mostram as **tendências**.',
  '',
  '### Leads por Origem',
  '',
  '```',
  '      🍕 Leads por Origem',
  '   ┌──────────────────────┐',
  '   │  SITE        35%  🟣 │',
  '   │  INDICACAO   25%  🟠 │',
  '   │  WHATSAPP    20%  🔵 │',
  '   │  FEIRA       15%  🟢 │',
  '   │  OUTRO        5%  🔴 │',
  '   └──────────────────────┘',
  '```',
  '',
  '> ❓ De onde vêm mais leads? Invista no que funciona!',
  '',
  '---',
  '',
  '### Outros gráficos',
  '',
  '| Gráfico | Pergunta | Ação |',
  '| :--- | :--- | :--- |',
  '| **Pipeline por Estágio** | Quanto dinheiro está parado? | Foque em fechar |',
  '| **Oport. por Representante** | Quem está com mais negócios? | Distribuir melhor |',
  '| **Propostas por Status** | Muitas recusadas? | Rever preços |',
  '| **Tarefas por Tipo** | Mais ligações ou reuniões? | Equilibrar atividades |',
  '| **Conversão** | Onde perdemos mais? | Treinar negociação |',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> **Compartilhe os relatórios com o time!** Os dados não mentem — eles mostram onde melhorar. 💙',
].join("\n")

lessons[16] = [
  '## 💬 WhatsApp integrado ao CRM',
  '',
  'As conversas de WhatsApp podem ser registradas automaticamente no CRM (via Evolution API + n8n).',
  '',
  '### Como funciona',
  '',
  '1. Cliente envia mensagem no WhatsApp comercial',
  '2. A mensagem **aparece automaticamente** no CRM',
  '3. Você vê: quem mandou, quando, o que disse',
  '4. Responda pelo CRM ou pelo WhatsApp normal',
  '',
  '---',
  '',
  '### Onde ver',
  '',
  '- Dentro da **Pessoa**, na aba **WhatsApp**',
  '- **CRM → WhatsApp** (lista geral)',
  '',
  '| Tipo | Quando |',
  '| :--- | :--- |',
  '| 📥 **RECEBIDA** | Cliente mandou |',
  '| 📤 **ENVIADA** | Você respondeu |',
  '',
  'Mensagens não lidas aparecem em destaque.',
  '',
  '---',
  '',
  '> 🔒 **Privacidade:** Só registra mensagens de contatos já cadastrados.',
].join("\n")

lessons[17] = [
  '## 📣 O que são Campanhas?',
  '',
  'Campanhas são **disparos de comunicação** para múltiplos contatos. Exemplos:',
  '- 🎄 "Feliz Natal!"',
  '- 🎂 "Feliz aniversário!"',
  '- 📢 "Novidade: tecido X acabou de chegar!"',
  '- 📰 "Newsletter mensal"',
  '',
  '---',
  '',
  '### Criando uma campanha',
  '',
  'Vá em **CRM → Campanhas → Nova Campanha**:',
  '',
  '| Campo | Descrição |',
  '| :--- | :--- |',
  '| **Nome** | Nome interno |',
  '| **Tipo** | WHATSAPP (por enquanto) |',
  '| **Descrição** | Para que serve |',
  '| **Data Início / Fim** | Período da campanha |',
  '| **Orçamento** | Quanto vai custar |',
  '| **Status** | ATIVA, PAUSADA, CONCLUIDA |',
  '',
  '---',
  '',
  '### Status',
  '',
  '| Status | Significado |',
  '| :---: | :--- |',
  '| 🟢 **ATIVA** | Campanha rodando |',
  '| 🟡 **PAUSADA** | Temporariamente parada |',
  '| ✅ **CONCLUIDA** | Finalizada |',
  '',
  'Após a campanha, registre: **Leads gerados** e **Custo de aquisição**.',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> **Campanha não é spam!** Dispare mensagens com **valor real** para o cliente.',
].join("\n")

lessons[18] = [
  '## 🤖 O que a IA Comercial faz?',
  '',
  'A **Inteligência Artificial Comercial** analisa dados para ajudar você a vender mais.',
  '',
  '### 1️⃣ Score de leads',
  '',
  'A IA analisa cada lead e dá uma nota de **0 a 100**:',
  '',
  '| Fator | O que avalia |',
  '| :--- | :--- |',
  '| Segmento | A Pessoa é de um segmento promissor? |',
  '| Porte | Pequena, média ou grande? |',
  '| Origem | Indicação vale mais que site |',
  '| Comportamento | Similar a clientes que converteram |',
  '',
  '| Score | Ação |',
  '| :---: | :--- |',
  '| 🟢 **70+** | Corre atrás! 🔥 |',
  '| 🟡 **40-69** | Mantenha contato |',
  '| 🔴 **< 40** | Talvez não seja o momento |',
  '',
  'Ordene a lista por score e atenda primeiro os maiores.',
  '',
  '---',
  '',
  '### 2️⃣ Resumo da Pessoa',
  '',
  'Na página da Pessoa, o card **"Resumo IA"** mostra:',
  '- 📝 Resumo automático dos dados',
  '- 💡 Sugestões de ações',
  '- 📊 Análise do potencial',
  '',
  '> 💡 **Exemplo:** "A Pessoa ABC é uma confecção de médio porte em São Paulo. Sugerimos abordar com amostras de malha."',
  '',
  '---',
  '',
  '### 3️⃣ Previsão de vendas',
  '',
  'A IA projeta quanto você deve vender no mês e nos próximos meses.',
  '',
  '### Botão "Reclassificar"',
  '',
  'Se novos dados entrarem, clique para a IA reavaliar.',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> **A IA é sua assistente, não sua chefe.** Ela sugere, você decide.',
].join("\n")

lessons[19] = [
  '## 🗺️ Organização Comercial',
  '',
  'O CRM organiza a força de vendas em hierarquia:',
  '',
  '```',
  '     ┌─────────────────────────┐',
  '     │     DIRETORIA           │',
  '     │  (visão de tudo)        │',
  '     └──────────┬──────────────┘',
  '                ⬇️',
  '     ┌─────────────────────────┐',
  '     │  GERENTE REGIONAL       │',
  '     │  (SP, RJ, MG, etc.)     │',
  '     └──────────┬──────────────┘',
  '                ⬇️',
  '     ┌─────────────────────────┐',
  '     │  REPRESENTANTE          │',
  '     │  (atende clientes)      │',
  '     └─────────────────────────┘',
  '```',
  '',
  '---',
  '',
  '### Regiões',
  '',
  'Cada **Região** corresponde a um estado ou área geográfica.',
  '',
  '| Região | Gerente |',
  '| :--- | :--- |',
  '| São Paulo | João Silva |',
  '| Rio de Janeiro | Maria Santos |',
  '| Minas Gerais | Carlos Pereira |',
  '',
  '### Equipes',
  '',
  'Dentro de cada região, as **Equipes** organizam os vendedores.',
  '',
  '| Equipe | Região | Responsável |',
  '| :--- | :--- | :--- |',
  '| Equipe Alpha | São Paulo | Pedro Costa |',
  '| Equipe Beta | São Paulo | Ana Lima |',
  '',
  '---',
  '',
  '### Como configurar?',
  '',
  '1. **CRM → Configurações**',
  '2. Cadastre as **Regiões**',
  '3. Cadastre as **Equipes** vinculadas',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> Regiões mudam, equipes se reestruturam. Mantenha tudo atualizado no CRM.',
].join("\n")

lessons[20] = [
  '## 🎓 Como usar este treinamento',
  '',
  '### Navegação',
  '',
  '1. Na página inicial, veja todos os **módulos** (caixinhas coloridas)',
  '2. **Clique em um módulo** para expandir e ver as lições',
  '3. **Clique em uma lição** para ler o conteúdo completo',
  '',
  '### Funcionalidades',
  '',
  '| Funcionalidade | Como usar |',
  '| :--- | :--- |',
  '| 📖 **Ler lição** | Clique no título |',
  '| 📄 **Exportar PDF** | Dentro da lição |',
  '| ⏪⏩ **Navegar** | Setas Anterior / Próxima |',
  '| ℹ️ **Info** | Clique no "i" |',
  '| 🔗 **Links POP** | Abre em nova aba |',
  '| 🎬 **Vídeos** | Tutoriais em vídeo |',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> Volte sempre que tiver dúvida. E se algo não estiver claro, avise o Tiago! 💙',
].join("\n")

lessons[21] = [
  '## 🌟 Rotina Diária Recomendada',
  '',
  '### ☀️ Manhã (10 min)',
  '',
  '| Horário | O que fazer |',
  '| :---: | :--- |',
  '| 08:00 | **Dashboard** — veja os números |',
  '| 08:05 | **Tarefas do dia** — o que precisa fazer |',
  '| 08:10 | **Leads novos** — atenda os com score alto |',
  '',
  '### 📅 Durante o dia',
  '',
  '- **Registre TUDO** — cada ligação, WhatsApp, contato',
  '- **Atualize status** — arraste oportunidades no Kanban',
  '- **Crie tarefas** — se prometeu algo, crie uma tarefa',
  '',
  '### 🌆 Fim do dia (5 min)',
  '',
  '- ✅ Marcar tarefas concluídas',
  '- 📝 Escrever relato de visitas',
  '- 📊 Ver o que ficou pendente',
  '',
  '---',
  '',
  '### Metas semanais',
  '',
  '| Indicador | Meta |',
  '| :--- | :---: |',
  '| 📞 Novos leads contatados | 5+ |',
  '| 💼 Novas oportunidades | 3+ |',
  '| 📄 Propostas enviadas | 2+ |',
  '| 📅 Visitas realizadas | 2+ |',
  '',
  '---',
  '',
  '### Mindset',
  '',
  '| Pensamento antigo | Pensamento novo |',
  '| :--- | :--- |',
  '| "Preencher CRM" | "Organizar minha vida" |',
  '| "Ter que registrar" | "Nunca mais esquecer" |',
  '| "Perder tempo" | "Investir no meu sucesso" |',
  '',
  '> Cada minuto no CRM é **investimento na sua carreira**. Mais vendas = mais comissão! 🤑',
  '',
  '---',
  '',
  '### O poder do hábito',
  '',
  '| Período | Sensação |',
  '| :--- | :--- |',
  '| Dias 1-7 | "Nossa, que trabalhoso..." |',
  '| Dias 8-30 | "Já estou pegando o jeito" |',
  '| Dias 31+ | "Não consigo mais viver sem CRM" |',
  '',
  '**Persista!** Em 30 dias o CRM vira parte de você. 🤝',
].join("\n")

lessons[22] = [
  '## 📜 As 10 Regras de Ouro do CRM',
  '',
  '### 1️⃣ 🥇 Se não está no CRM, não aconteceu',
  '',
  'Ligou, visitou, mandou WhatsApp, enviou proposta? **Registre**.',
  '',
  '### 2️⃣ 👤 Pessoa primeiro, sempre',
  '',
  'Antes de cadastrar lead, contato ou oportunidade, **verifique se a Pessoa já existe**.',
  '',
  '### 3️⃣ 🔍 Dados limpos = Dados úteis',
  '',
  '- Sem abreviações ("Companhia Têxtil", não "Cia Txt")',
  '- CNPJ com pontuação',
  '- Segmento correto',
  '- E-mail válido',
  '',
  '### 4️⃣ 📝 Relatos completos',
  '',
  'Escreva como se outro vendedor fosse assumir amanhã.',
  '',
  '### 5️⃣ 🔄 Atualize os status',
  '',
  'Não deixe oportunidade em "NOVO" por semanas.',
  '',
  '### 6️⃣ 🤝 Compartilhe informação',
  '',
  'Um lead que não serve pra você pode ser perfeito pra outro colega.',
  '',
  '### 7️⃣ 💬 Cliente não é número',
  '',
  'Atrás de cada registro **tem uma pessoa**. Trate com respeito.',
  '',
  '### 8️⃣ 📊 Dados geram decisões',
  '',
  'A diretoria usa os relatórios para decidir investimentos.',
  '',
  '### 9️⃣ ❓ Dúvida? Pergunte!',
  '',
  'Consulte o treinamento, um colega ou seu gerente.',
  '',
  '### 🔟 🎯 Venda com amor',
  '',
  'Cliente bem atendido volta, indica e confia na PDM Têxtil.',
  '',
  '---',
  '',
  '> 💙 *"Criei este CRM com carinho para facilitar seu dia a dia. Use, explore, erre, aprenda, pergunte, melhore. Este CRM é nosso!" — O Desenvolvedor* 🚀',
].join("\n")

lessons[23] = [
  '## 🏢 O que é um Cliente?',
  '',
  '**Cliente** é uma Pessoa que já tem relacionamento comercial ativo. Diferente de uma **Pessoa** (prospecto), o cliente está na base comercial com representantes.',
  '',
  '| Pessoa (CRM) | Cliente (Comercial) |',
  '| :--- | :--- |',
  '| Qualquer Pessoa cadastrada | Pessoa com relacionamento comercial |',
  '| Pode ser prospecto | Já compra ou já comprou |',
  '| Visão completa do CRM | Visão comercial com representantes |',
  '| Cadastrada em CRM → Pessoas | Gerenciada em Comercial → Clientes |',
  '',
  '> 💡 Toda Pessoa pode se tornar um cliente.',
  '',
  '---',
  '',
  '### Acessando',
  '',
  'Vá em **Comercial → Clientes**. Busque por nome, CNPJ ou representante.',
  '',
  '### Funcionalidades',
  '',
  '| Ação | Como fazer |',
  '| :--- | :--- |',
  '| 🔍 Buscar | Por nome, CNPJ ou representante |',
  '| 📄 Ver detalhes | Clique no cliente |',
  '| ✏️ Editar | Dentro do cliente, Editar |',
  '| 👥 Representantes | Gerenciar representantes |',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> Mantenha os clientes sempre atualizados! Dados corretos = atendimento de qualidade.',
].join("\n")

lessons[24] = [
  '## 👤 O que é um Representante?',
  '',
  'O **Representante** é o profissional de vendas que atende os clientes em campo.',
  '',
  '---',
  '',
  '### Cadastrando',
  '',
  'Vá em **Comercial → Representantes → Novo Representante**:',
  '',
  '| Campo | Obrigatório | Descrição |',
  '| :--- | :---: | :--- |',
  '| **Nome** | ✅ Sim | Nome completo |',
  '| **CPF** | Não | CPF com pontuação |',
  '| **Email** | Não | E-mail |',
  '| **Telefone / Celular** | Não | Contato |',
  '| **Endereço** | Não | Logradouro, número, bairro, cidade, UF |',
  '| **Status** | Padrão: ATIVO | ATIVO, INATIVO |',
  '| **Gerente** | Não | Usuário gerente responsável |',
  '',
  '---',
  '',
  '### Vinculando a clientes',
  '',
  '- **Pelo cliente:** Abra o cliente, seção Representantes, Adicionar',
  '- **Pelo representante:** Gerencie os vínculos',
  '',
  'Representantes também são organizados em **Equipes** (CRM → Equipes).',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> Representante bem cadastrado = gestão eficiente. Relatórios por representante, distribuição inteligente de leads.',
].join("\n")

lessons[25] = [
  '## 🗺️ Estados no CRM',
  '',
  'A tabela de **Estados** é usada em endereços de Pessoas, clientes, representantes e regiões.',
  '',
  'Vá em **CRM → Estados**.',
  '',
  '| Ação | Descrição |',
  '| :--- | :--- |',
  '| 📋 Ver lista | Todos os estados com UF, nome e país |',
  '| ➕ Adicionar | Preencha UF, nome e país |',
  '| ✏️ Editar | Clique no nome ou UF |',
  '| ❌ Excluir | Só se nenhuma cidade estiver vinculada |',
  '',
  '| Campo | Obrigatório | Descrição |',
  '| :--- | :---: | :--- |',
  '| **UF** | ✅ Sim | Sigla de 2 letras (SP) |',
  '| **Nome** | ✅ Sim | Nome completo (São Paulo) |',
  '| **País** | ✅ Sim | País (Brasil) |',
  '',
  '> 🌎 Todos os 27 estados brasileiros já estão cadastrados.',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> Antes de cadastrar, verifique se já existe. Use UF em maiúsculo.',
].join("\n")

lessons[26] = [
  '## 🏙️ Cidades no CRM',
  '',
  'As **Cidades** são usadas nos endereços de toda a base.',
  '',
  'Vá em **CRM → Cidades**.',
  '',
  '| Ação | Como fazer |',
  '| :--- | :--- |',
  '| 🔍 Buscar | Digite nome da cidade ou UF |',
  '| ➕ Adicionar | Selecione o estado, digite o nome |',
  '| 📊 Filtrar | Veja cidades de um estado |',
  '',
  '### Como adicionar',
  '',
  '1. Clique em **Adicionar Cidade**',
  '2. Selecione o **Estado**',
  '3. Digite o **Nome** (com acento)',
  '4. Confirme',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> Se uma cidade não existir, crie! Endereço sem cidade não aparece nos relatórios.',
].join("\n")

lessons[27] = [
  '## 🌍 Países e códigos DDI',
  '',
  'A tabela de **Países** contém todos os países do mundo com seus códigos DDI.',
  '',
  'Vá em **CRM → Países**.',
  '',
  '| Coluna | Exemplo | Descrição |',
  '| :--- | :--- | :--- |',
  '| **Nome** | Brasil | Nome oficial |',
  '| **Código DDI** | +55 | Código internacional |',
  '| **Total de Estados** | 27 | Estados vinculados |',
  '',
  '| Ação | Descrição |',
  '| :--- | :--- |',
  '| 📋 Ver lista | 217 países reconhecidos pela ONU |',
  '| ➕ Adicionar | Nome e código DDI |',
  '| ✏️ Editar | Clique no botão |',
  '| ❌ Excluir | Só se nenhum estado vinculado |',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> Os 217 países já vêm pré-cadastrados com DDI. Raramente precisará adicionar um novo.',
].join("\n")

lessons[28] = [
  '## 👥 O que são Equipes?',
  '',
  'Equipes são **grupos de representantes** organizados para atender uma região ou mercado.',
  '',
  '```',
  'REGIÃO: São Paulo',
  '├── EQUIPE ALPHA',
  '│   ├── João',
  '│   ├── Maria',
  '│   └── Pedro',
  '└── EQUIPE BETA',
  '    ├── Ana',
  '    └── Carlos',
  '```',
  '',
  '---',
  '',
  '### Criando uma equipe',
  '',
  'Vá em **CRM → Equipes → Nova Equipe**:',
  '',
  '| Campo | Obrigatório | Descrição |',
  '| :--- | :---: | :--- |',
  '| **Nome** | ✅ Sim | Nome da equipe |',
  '| **Região** | Não | Região geográfica |',
  '| **Responsável** | Sim | Quem lidera |',
  '',
  'Região é opcional — útil para equipes especiais.',
  '',
  '---',
  '',
  '### Gerenciando membros',
  '',
  '**Adicionar:** Busque o representante (2+ letras) e clique em Adicionar.',
  '',
  '**Remover:** Clique em Remover. O representante não é excluído do sistema.',
  '',
  '| Info | Detalhe |',
  '| :--- | :--- |',
  '| 👤 Nome | Nome completo |',
  '| 📍 Cidade / UF | Localização |',
  '| 📞 Celular | Telefone |',
  '| 📧 Email | E-mail |',
  '',
  '---',
  '',
  '### Editando / excluindo',
  '',
  '- **Editar:** Clique no lápis (✏️)',
  '- **Excluir:** Clique na lixeira (🗑️). Apenas ADMIN/SUDO.',
  '',
  '---',
  '',
  '### 💡 Dica de ouro',
  '',
  '> Organize por critérios claros: região, tipo de cliente ou porte. Revise periodicamente!',
].join("\n")

// ─────────── Update DB ───────────
// Fix pré-requisitos
await sql`UPDATE crm_treino_licoes SET pre_requisitos = REPLACE(pre_requisitos, 'Empresas cadastradas (opcional para vincular)', 'Pessoas cadastradas (opcional para vincular)') WHERE pre_requisitos LIKE '%Empresas cadastradas%'`

let count = 0
for (const [id, md] of Object.entries(lessons)) {
  if (!md) continue
  await sql`UPDATE crm_treino_licoes SET conteudo_md = ${md} WHERE id = ${Number(id)}`
  count++
  console.log(`✅ ID ${id}`)
}

console.log(`\n🏁 ${count} lições atualizadas!`)
process.exit(0)
